#!/usr/bin/env node

/**
 * Setup Script for Idol Be Backend
 * This script helps users set up the backend quickly
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function question(query) {
    return new Promise((resolve) => {
        rl.question(query, resolve);
    });
}

async function setupEnvironment() {
    console.log('\n🎮 Welcome to Idol Be Backend Setup!\n');
    
    const envPath = '.env';
    const examplePath = '.env.example';
    
    // Check if .env already exists
    if (fs.existsSync(envPath)) {
        const overwrite = await question('📁 .env file already exists. Do you want to overwrite it? (y/N): ');
        if (overwrite.toLowerCase() !== 'y') {
            console.log('✅ Using existing .env file.');
            rl.close();
            return;
        }
    }
    
    console.log('\n🔧 Let\'s configure your environment variables:\n');
    
    // Get configuration from user
    const config = {};
    
    // Server Configuration
    console.log('📡 Server Configuration:');
    config.PORT = await question('Enter server port (default: 5000): ') || '5000';
    config.NODE_ENV = 'development';
    
    // Database Configuration
    console.log('\n🗄️ Database Configuration:');
    const useLocal = await question('Use local MongoDB? (Y/n): ');
    if (useLocal.toLowerCase() !== 'n') {
        config.MONGODB_URI = 'mongodb://localhost:27017/idolbe';
    } else {
        config.MONGODB_URI = await question('Enter MongoDB Atlas connection string: ');
    }
    
    // JWT Configuration
    console.log('\n🔐 Security Configuration:');
    const jwtSecret = await question('Enter JWT secret (leave empty to generate): ');
    config.JWT_SECRET = jwtSecret || generateSecret();
    
    // Cloudinary Configuration
    console.log('\n☁️ Cloudinary Configuration:');
    console.log('You need a Cloudinary account. Sign up at https://cloudinary.com if you don\'t have one.');
    config.CLOUDINARY_CLOUD_NAME = await question('Enter Cloudinary Cloud Name: ');
    config.CLOUDINARY_API_KEY = await question('Enter Cloudinary API Key: ');
    config.CLOUDINARY_API_SECRET = await question('Enter Cloudinary API Secret: ');
    
    // Admin Configuration
    console.log('\n👑 Admin Configuration:');
    const useDefaultAdmin = await question('Use default admin credentials? (Y/n): ');
    if (useDefaultAdmin.toLowerCase() !== 'n') {
        config.ADMIN_EMAIL = 'idolbeadmin@idolbe.com';
        config.ADMIN_PASSWORD = 'theidol234';
    } else {
        config.ADMIN_EMAIL = await question('Enter admin email: ');
        config.ADMIN_PASSWORD = await question('Enter admin password: ');
    }
    
    // Frontend URL
    console.log('\n🌐 Frontend Configuration:');
    config.FRONTEND_URL = await question('Enter frontend URL (default: http://localhost:5173): ') || 'http://localhost:5173';
    
    // Create .env file
    const envContent = `# Environment Configuration for Idol Be Backend
# Generated by setup script on ${new Date().toISOString()}

# Server Configuration
NODE_ENV=${config.NODE_ENV}
PORT=${config.PORT}

# Database Configuration
MONGODB_URI=${config.MONGODB_URI}

# JWT Configuration
JWT_SECRET=${config.JWT_SECRET}
JWT_EXPIRES_IN=7d

# Cloudinary Configuration
CLOUDINARY_CLOUD_NAME=${config.CLOUDINARY_CLOUD_NAME}
CLOUDINARY_API_KEY=${config.CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET=${config.CLOUDINARY_API_SECRET}

# Admin Configuration
ADMIN_EMAIL=${config.ADMIN_EMAIL}
ADMIN_PASSWORD=${config.ADMIN_PASSWORD}

# Security Configuration
BCRYPT_ROUNDS=12

# CORS Configuration
FRONTEND_URL=${config.FRONTEND_URL}

# Upload Configuration
MAX_FILE_SIZE=104857600

# Rate Limiting
RATE_LIMIT_WINDOW=15
RATE_LIMIT_MAX=1000

# Development Configuration
DEBUG=true
LOG_LEVEL=debug
`;

    fs.writeFileSync(envPath, envContent);
    
    console.log('\n✅ Environment configuration saved to .env');
    console.log('\n🚀 Next Steps:');
    console.log('1. Install dependencies: npm install');
    console.log('2. Start the server: npm run dev');
    console.log('3. Access admin panel: http://localhost:' + config.PORT + '/admin');
    console.log('4. Use admin credentials:');
    console.log(`   Email: ${config.ADMIN_EMAIL}`);
    console.log(`   Password: ${config.ADMIN_PASSWORD}`);
    
    rl.close();
}

function generateSecret() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*';
    let secret = '';
    for (let i = 0; i < 64; i++) {
        secret += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return secret;
}

// Run setup if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
    setupEnvironment().catch(console.error);
}

export { setupEnvironment };